# Generated by Django 5.2.11 on 2026-03-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_websitechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitechunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
